version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo-master
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-master
      ME_CONFIG_MONGODB_ADMINUSERNAME:
      ME_CONFIG_MONGODB_ADMINPASSWORD:

  mongo-master:
    image: mongo:4.1
    container_name: mongo-master
    ports:
      - "27017:27017"
    expose:
      - "27017"
    command: mongod --master

  mongo-slave1:
    image: mongo:4.1
    container_name: mongo-slave1
    ports:
      - "27117:27017"
    expose:
      - "27017"
    command: mongod --slave --source mongo-master:27017

  mongo-slave2:
    image: mongo:4.1
    container_name: mongo-slave2
    ports:
      - "27127:27017"
    expose:
      - "27017"
    command: mongod --slave --source mongo-master:27017

networks:
  default:
    external:
      name: local-network
